CREATE DATABASE credit_card_db;
USE credit_card_db;


CREATE TABLE churn_data (
    Client_Num INT PRIMARY KEY,
    Attrition_Flag VARCHAR(50),
    Customer_Age INT,
    Gender VARCHAR(10),
    Dependent_count INT,
    Education_Level VARCHAR(50),
    Marital_Status VARCHAR(50),
    Income_Category VARCHAR(50),
    Card_Category VARCHAR(50),
    Months_on_book INT,
    Total_Relationship_Count INT,
    Months_Inactive_12_mon INT,
    Contacts_Count_12_mon INT,
    Credit_Limit DECIMAL(10, 2),
    Total_Revolving_Bal DECIMAL(10, 2),
    Avg_Open_To_Buy DECIMAL(10, 2),
    Total_Amt_Chng_Q4_Q1 DECIMAL(6, 4),
    Total_Trans_Amt DECIMAL(10, 2),
    Total_Trans_Ct INT,
    Total_Ct_Chng_Q4_Q1 DECIMAL(6, 4),
    Avg_Utilization_Ratio DECIMAL(6, 4),
    Age_Group VARCHAR(50),
    Tenure_Years DECIMAL(5, 2),
    Avg_Trans_Value DECIMAL(10, 2),
    Utilization_Tier VARCHAR(50)
);





-- 1. Total number of unique accounts in the portfolio
SELECT COUNT(Client_Num) AS Total_Unique_Accounts 
FROM churn_data;








-- 2. Raw count of active versus attrited customers
SELECT Attrition_Flag, COUNT(*) AS Customer_Count 
FROM churn_data 
GROUP BY Attrition_Flag;








-- 3. Exact percentage of customers who have churned across the entire portfolio
SELECT 
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS Exact_Churn_Percentage 
FROM churn_data;







-- 4. Total annual transaction amount generated by all accounts combined
SELECT SUM(Total_Trans_Amt) AS Total_Annual_Transaction_Amount 
FROM churn_data;







-- 5. Mean credit limit extended across the entire customer base
SELECT AVG(Credit_Limit) AS Mean_Credit_Limit 
FROM churn_data;







-- 6. Gender distribution of the customer portfolio
SELECT Gender, COUNT(*) AS Customer_Count, 
       (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM churn_data)) AS Percentage
FROM churn_data
GROUP BY Gender;







-- 7. Average age of customers in the dataset
SELECT AVG(Customer_Age) AS Avg_Customer_Age 
FROM churn_data;










-- 8. Customer distribution across tenure clusters based on months on book
SELECT Months_on_book, COUNT(*) AS Customer_Count 
FROM churn_data 
GROUP BY Months_on_book 
ORDER BY Months_on_book;











-- 9. Customer count per card category (Blue, Silver, Gold, Platinum)
SELECT Card_Category, COUNT(*) AS Customer_Count 
FROM churn_data 
GROUP BY Card_Category;











-- 10. Average revolving balance carried on cards
SELECT AVG(Total_Revolving_Bal) AS Avg_Revolving_Balance 
FROM churn_data;









-- 11. Churn percentage by card category to find which suffers highest attrition
SELECT 
    Card_Category, 
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Churned_Customers,
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS Churn_Rate_Percentage
FROM churn_data 
GROUP BY Card_Category 
ORDER BY Churn_Rate_Percentage DESC;







-- 12. Customer service contact frequency vs. churn rate
SELECT 
    Contacts_Count_12_mon, 
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Churned_Customers,
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS Churn_Rate_Percentage
FROM churn_data
GROUP BY Contacts_Count_12_mon
ORDER BY Contacts_Count_12_mon;










-- 13. Income category attrition risk
SELECT 
    Income_Category, 
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Churned_Customers,
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS Churn_Rate_Percentage
FROM churn_data
GROUP BY Income_Category
ORDER BY Churn_Rate_Percentage DESC;














-- 14. Months of inactivity vs. customer defection rates
SELECT 
    Months_Inactive_12_mon, 
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Churned_Customers,
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS Churn_Rate_Percentage
FROM churn_data
GROUP BY Months_Inactive_12_mon
ORDER BY Months_Inactive_12_mon;









-- 15. Average total transaction amount contrast between active and attrited customers
SELECT 
    Attrition_Flag, 
    AVG(Total_Trans_Amt) AS Avg_Total_Transaction_Amount,
    AVG(Total_Trans_Ct) AS Avg_Total_Transaction_Count
FROM churn_data
GROUP BY Attrition_Flag;









-- 16. Revolving balances drop-off prior to churn
SELECT 
    Attrition_Flag, 
    AVG(Total_Revolving_Bal) AS Avg_Revolving_Balance
FROM churn_data
GROUP BY Attrition_Flag;









-- 17. Customer acquisition and churn distributions across education brackets
SELECT 
    Education_Level, 
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Churned_Customers,
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS Churn_Rate_Percentage
FROM churn_data
GROUP BY Education_Level
ORDER BY Total_Customers DESC;










-- 18. Average credit utilization ratio compared across active and churned segments
SELECT 
    Attrition_Flag, 
    AVG(Avg_Utilization_Ratio) AS Avg_Utilization_Ratio
FROM churn_data
GROUP BY Attrition_Flag;












-- 19. Total number of products/services held (Total Relationship Count) effect on retention
SELECT 
    Total_Relationship_Count, 
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Churned_Customers,
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS Churn_Rate_Percentage
FROM churn_data
GROUP BY Total_Relationship_Count
ORDER BY Total_Relationship_Count;












-- 20. Transaction amount change between Q4 and Q1 across churn statuses
SELECT 
    Attrition_Flag, 
    AVG(Total_Amt_Chng_Q4_Q1) AS Avg_Amount_Change_Q4_Q1,
    AVG(Total_Ct_Chng_Q4_Q1) AS Avg_Count_Change_Q4_Q1
FROM churn_data
GROUP BY Attrition_Flag;











-- 21. Churn concentration across credit limit deciles using window functions
WITH DecileCTE AS (
    SELECT 
        Client_Num,
        Credit_Limit,
        Attrition_Flag,
        NTILE(10) OVER (ORDER BY Credit_Limit DESC) AS Credit_Decile
    FROM churn_data
)
SELECT 
    Credit_Decile,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Churned_Customers,
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS Churn_Rate_Percentage
FROM DecileCTE
GROUP BY Credit_Decile
ORDER BY Credit_Decile;











-- 22. Corrected query for low-spending outlier accounts
SELECT 
    Client_Num,
    Total_Trans_Amt,
    Attrition_Flag
FROM churn_data
WHERE Total_Trans_Amt < (
    SELECT AVG(Total_Trans_Amt) - (1 * STDDEV(Total_Trans_Amt)) 
    FROM churn_data
);







-- 23. Highest-spending customers inside each card category using DENSE_RANK()
WITH RankedSpendCTE AS (
    SELECT 
        Client_Num,
        Card_Category,
        Total_Trans_Amt,
        DENSE_RANK() OVER (PARTITION BY Card_Category ORDER BY Total_Trans_Amt DESC) AS Spend_Rank
    FROM churn_data
)
SELECT 
    Client_Num,
    Card_Category,
    Total_Trans_Amt,
    Spend_Rank
FROM RankedSpendCTE
WHERE Spend_Rank <= 5;










-- 24. Cumulative transaction volume ordered by total transaction amount
SELECT 
    Client_Num,
    Total_Trans_Amt,
    SUM(Total_Trans_Amt) OVER (ORDER BY Total_Trans_Amt DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS Cumulative_Revenue
FROM churn_data;














-- 25. Churn rate across precise risk tiers categorized by utilization ratios
WITH UtilizationTierCTE AS (
    SELECT 
        Client_Num,
        Attrition_Flag,
        CASE 
            WHEN Avg_Utilization_Ratio = 0 THEN 'Zero Utilization (0%)'
            WHEN Avg_Utilization_Ratio < 0.3 THEN 'Low (0.01 - 0.29)'
            WHEN Avg_Utilization_Ratio < 0.6 THEN 'Moderate (0.30 - 0.59)'
            ELSE 'High (0.60+)'
        END AS Utilization_Tier
    FROM churn_data
)
SELECT 
    Utilization_Tier,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Churned_Customers,
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS Churn_Rate_Percentage
FROM UtilizationTierCTE
GROUP BY Utilization_Tier
ORDER BY Churn_Rate_Percentage DESC;












-- 26. Actual churn count for high-risk profiles meeting multiple friction criteria simultaneously
SELECT 
    COUNT(*) AS High_Risk_Profile_Count,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Actual_Churned_Count
FROM churn_data
WHERE Contacts_Count_12_mon >= 4 
  AND Months_Inactive_12_mon >= 3;
  
  
  
  
  
  
  
  
  
  
-- 27. Corrected Credit Limit Summary Matrix
SELECT 
    Income_Category,
    COALESCE(AVG(CASE WHEN Gender = 'Male' THEN Credit_Limit END), 0) AS Male_Avg_Credit_Limit,
    COALESCE(AVG(CASE WHEN Gender = 'Female' THEN Credit_Limit END), 0) AS Female_Avg_Credit_Limit,
    AVG(Credit_Limit) AS Overall_Avg_Credit_Limit
FROM churn_data
GROUP BY Income_Category
ORDER BY Income_Category;




-- 28. Row numbers assigned to customers ordered by account tenure (Months_on_book) within each income bracket
SELECT 
    Client_Num,
    Income_Category,
    Months_on_book,
    ROW_NUMBER() OVER (PARTITION BY Income_Category ORDER BY Months_on_book DESC) AS Tenure_Row_Num
FROM churn_data;









-- 29. Customers possessing high credit limits ($15,000+) but recording minimal transaction counts (<20)
SELECT 
    Client_Num,
    Credit_Limit,
    Total_Trans_Ct,
    Attrition_Flag
FROM churn_data
WHERE Credit_Limit >= 15000 
  AND Total_Trans_Ct < 20;










-- 30. Comparative churn density across generational age cohorts
WITH AgeCohortCTE AS (
    SELECT 
        Client_Num,
        Attrition_Flag,
        CASE 
            WHEN Customer_Age < 30 THEN 'Under 30 (Gen Z / Young)'
            WHEN Customer_Age BETWEEN 30 AND 49 THEN '30-49 (Millennials / Gen X)'
            WHEN Customer_Age BETWEEN 50 AND 64 THEN '50-64 (Boomers)'
            ELSE '65+ (Silent / Senior)'
        END AS Age_Cohort
    FROM churn_data
)
SELECT 
    Age_Cohort,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) AS Churned_Customers,
    (SUM(CASE WHEN Attrition_Flag = 'Attrited Customer' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS Churn_Rate_Percentage
FROM AgeCohortCTE
GROUP BY Age_Cohort
ORDER BY Churn_Rate_Percentage DESC;


























































